[server]
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#007aff"
backgroundColor = "#f5f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#1d1d1f"
font = "sans serif"

[browser]
gatherUsageStats = false
